# Generated by Django 5.0.2 on 2024-03-24 19:15

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Australian', 'Australian'), ('Netherlands', 'Netherlands'), ('Pakistani', 'Pakistani')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('location', models.CharField(max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_address', models.TextField(blank=True, null=True)),
                ('size_in_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('farm_type', models.CharField(blank=True, max_length=50, null=True)),
                ('barns', models.PositiveIntegerField(default=0)),
                ('sheds', models.PositiveIntegerField(default=0)),
                ('irrigation_system', models.BooleanField(default=False)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profits', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('date_of_birth', models.DateField(error_messages={'max_value': 'The date of birth cannot be in the future'}, validators=[django.core.validators.MaxValueValidator(datetime.date.today)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1)),
                ('availability_status', models.CharField(choices=[('A', 'Alive'), ('D', 'Dead'), ('S', 'Sold')], default='A', max_length=1)),
                ('pregnancy_status', models.CharField(choices=[('P', 'Pregnant'), ('C', 'Calved'), ('N', 'Not pregnant')], default='N', max_length=1)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cows', to='dairymanagementsystem.animaltype')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='dairymanagementsystem.farm')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_factors', to='dairymanagementsystem.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='dairymanagementsystem.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dairymanagementsystem.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dairymanagementsystem.farm')),
            ],
        ),
        migrations.CreateModel(
            name='HealthSafetyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_safety_records', to='dairymanagementsystem.farm')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='dairymanagementsystem.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Milk_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milking_time_value', models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening'), (4, 'Night')])),
                ('milking_date', models.DateTimeField(auto_now_add=True)),
                ('amount_in_kgs', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Amount of milk cannot be less than 0 kgs')], verbose_name='Amount (kg)')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk', to='dairymanagementsystem.animal')),
            ],
            options={
                'verbose_name_plural': 'Milk',
                'unique_together': {('cow', 'milking_time_value')},
            },
        ),
    ]
