# Generated by Django 5.0.2 on 2024-04-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairymanagementsystem', '0003_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='AnimalType',
        ),
    ]
